# Generated by Django 5.1.4 on 2024-12-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaper',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='subject',
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='exam_type',
            field=models.CharField(choices=[('Semester', 'Semester'), ('Competitive', 'Competitive')], max_length=100),
        ),
    ]
