# Generated by Django 5.1.4 on 2024-12-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
