# Generated by Django 5.1.4 on 2024-12-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_remove_community_members_alter_community_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='community_thumbnails/'),
        ),
    ]
